In [1]:
# modules
import numpy as np

In [2]:
# helper functions
def relu(x):
    return np.maximum(x,0)

def softmax(z):
    return np.exp(z)/(np.sum(np.exp(z),axis=1))[:,np.newaxis]

def forward(X,parameters):
    # Unpacking parameters    
    W1,b1,W2,b2,V,c = parameters
    # Forward pass
    a1 = X.dot(W1) + b1
    H1 = relu(a1)
    a2 = H1.dot(W2) + b2
    H2 = relu(a2)
    a3 = H2.dot(V) + c
    Y_hat = softmax(a3)
    return Y_hat

In [3]:
# 3. Write out the function in python, call it ff nn 2 ReLu(...)
def ff_nn_2_Relu(W1,b1,W2,b2,V,c,X):
    pred_probs = forward(X,(W1,b1,W2,b2,V,c))
    print('X :\n{}\nY_hat :\n{}'.format(X, pred_probs))

In [4]:
# 4. Suppose you have the following set of weight matrices: 
# what are the class probabilities associated with the forward pass of each sample?
W1 = np.array([[1,-1],[0,0],[0,0.5]]).T
b1 = np.array([0,0,1])
W2 = np.array([[1,-1,0],[-1,0,0]]).T
b2 = np.array([1,-1])
V = np.array([[1,0],[-1,1],[0,-1]]).T
c = np.array([1,0,0])
X = np.array([[1, 0, 0], [-1, -1, 1]]).T
ff_nn_2_Relu(W1,b1,W2,b2,V,c,X)

X :
[[ 1 -1]
 [ 0 -1]
 [ 0  1]]
Y_hat :
[[9.81135202e-01 8.94679497e-04 1.79701181e-02]
 [9.46499123e-01 6.37746092e-03 4.71234165e-02]
 [8.43794734e-01 4.20100661e-02 1.14195199e-01]]
