In [1]:
# modules
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# helper functions
def relu(x):
    return np.maximum(x,0)

def relu_derivative(x):
    return np.where(x>0, 1, 0)

def softmax(z):
    return np.exp(z)/(np.sum(np.exp(z),axis=1))[:,np.newaxis]

def forward(X,parameters):
    # Unpacking parameters    
    W1,b1,W2,b2,V,c = parameters
    # Forward pass
    a1 = X.dot(W1) + b1
    H1 = relu(a1)
    a2 = H1.dot(W2) + b2
    H2 = relu(a2)
    a3 = H2.dot(V) + c
    Y_hat = softmax(a3)
    return Y_hat

def ff_nn_2_Relu(W1,b1,W2,b2,V,c,X):
    pred_probs = forward(X,(W1,b1,W2,b2,V,c))
    print('X : {}\nY_hat :\n{}'.format(X, pred_probs))


In [3]:
def main():
    W1 = np.array([1,-1,0,0,0,0.5]).reshape((2,3))
    b1 = np.array([0,0,1])
    W2 = np.array([1,-1,0,-1,0,0]).reshape((3,2))
    b2 = np.array([1,-1]).reshape((2,1))
    V = np.array([1,0,-1,1,0,-1]).reshape((2,3))
    c = np.array([1,0,0]).reshape((1,3))
    X = {
        0 : np.array([1,-1]).reshape((1,2)),
        1 : np.array([0,-1]).reshape((1,2)),
        2 : np.array([0,1]).reshape((1,2))
    }
    for i in X.keys():
        ff_nn_2_Relu(W1,b1,W2,b2,V,c,X[i])
        print('\n')

main()

X : [[ 1 -1]]
Y_hat :
[[0.94649912 0.04712342 0.00637746]
 [0.57611688 0.21194156 0.21194156]]


X : [[ 0 -1]]
Y_hat :
[[0.94649912 0.04712342 0.00637746]
 [0.57611688 0.21194156 0.21194156]]


X : [[0 1]]
Y_hat :
[[0.94649912 0.04712342 0.00637746]
 [0.57611688 0.21194156 0.21194156]]


